### ISSUE TITLE
Using django-angular with django-bootstrap3

### ISSUE THREAD

**Issue by vatsalj** [dyve/django-bootstrap3#239]
Hi,

I wanted to show a ModelForm with django-angular mixins in bootstrap style, for which I used django-bootstrap3, but it the two don't seem to be working together properly:

![image](https://cloud.githubusercontent.com/assets/1089034/7221105/6514fca6-e6fc-11e4-80d3-a7f9a87f51a3.png)

My ModelForm is this:

```python
class InfoForm(NgModelFormMixin, NgFormValidationMixin, NgModelForm):
    form_name = 'InfoForm'
    class Meta:
        model = models.InfoModel
```

What can be done to make django-bootstrap3 work well with django-angular forms?

**Comment by dyve** [comment]
I don't know. I wrote this library to be compatible with standard Django Forms, and to respect their settings. It look like the Angular Forms take another approach, and heavily modify or even replace standard Django forms.

Since I don't use the angular forms library, I won't be able to make a fix for this. Even if a pull request with a fix is submitted, I'll have to see if it is generic enough to be merged.

Thanks!

**Comment by dyve** [comment]
I'm closing this because I don't expect we'll be supporting other forms libraries
