### ISSUE TITLE
Django 1.9: template tag output needs to be marked as safe

### ISSUE THREAD

**Issue by jaddison** [dyve/django-bootstrap3#266]
Edit: I know that Django 1.9 hasn't been released yet. :)

Django 1.9 tightens up some security around template tags: https://docs.djangoproject.com/en/dev/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape

This change in Django is causing the `bootstrap_form` template tag to output the form markup as text instead of an actual form - ie. you see the html markup for the fields rather than the fields themselves.

**Comment by dyve** [comment]
Thanks @jaddison, will check it out.

**Comment by maxlemieux** [comment]
This also affects other template tags which return HTML. Fixed by wrapping simple_tag returns in mark_safe().

**Comment by dyve** [comment]
This is a really nasty change for `django-bootstrap3`, because there is extensive use of `simple_tag`.

The quick fix is to just `mark_safe` everything, which wil give the exact same behavior as before. This does however make the code quite ugly.

I have tried to use `format_html`, but it does not play nice with other utilities such as `flatatt`. Also, it turns out that adding or joining 2 safe strings results in an unsafe string (unless I made a mistake there).

Because of Django's rapid releases and the widespread use of `django-bootstrap3` I will start using `mark_safe` unless a better solution comes along (maybe no longer use `simple_tag`?). If anyone has input, it would be very welcome.

**Comment by dyve** [comment]
The development branch now passes test with Django 1.9 (from GitHub). Feedback welcome.

**Comment by dyve** [comment]
Of course, now < 1.8 fails because there is no `format_html` ...

**Comment by dyve** [comment]
Further investigation shows that supporting Django 1.9/1.10 and Django < 1.8 will results in lots of conditional code (try ... except ImportError).

**Comment by jaddison** [comment]
Is this something worth taking up with django devs on the dev making list?

**Comment by catskul** [comment]
This appears to still be a problem with django 1.8.x

**Comment by dyve** [comment]
@catskul I don't see the error in 1.8. Please provide more information, if possible a (new) test that fails.

**Comment by catskul** [comment]
unfortunately I dont have the resources to do so at the moment. I pinned my requirements to 6.1.0 which seemed to solve the problem for me (6.2.x all resulted in escaped html ending up in my forms)

If I have a chance to come up for air, I'll try to do more verification and possibly a test case.

**Comment by dyve** [comment]
Quite strange. If you have more info, please let me know.

**Comment by goetzb** [comment]
Maybe this is resolved by now as the last comment is from August 2015. Anyway, I just thought I'd add a reference to what I believe the reason for this behaviour is, as listed in the Django 1.9 release notes: https://docs.djangoproject.com/en/1.9/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape 

> In Django 1.9 [...] if the template context has autoescape=True set (the default), then simple_tag will wrap the output of the tag function with conditional_escape().

So you can probably turn it off and revert to the old behaviour by setting `autoescape=false` for the relevant template tags.
