### ISSUE TITLE
Feature request: data attributes to bootstrap_button.

### ISSUE THREAD

**Issue by TheDegree0** [dyve/django-bootstrap3#376]
It would be nice to be able to give bootstrap_button data attributes, so it can be used with JavaScript.

Example 1:
`{% bootstrap_button _('Button text') button_type='button' button_class='pull-right' data-attr1='Hello' data-attr2='World' %}`

Example 2:
`{% bootstrap_button _('Button text') button_type='button' button_class='pull-right' data='{"attr1": "Hello", "attr2": "World"}' %}`

**Comment by dyve** [comment]
Good idea. Requires further analysis since any HTML tag can have data attributes, so it should be possible to expand beyond buttons.

**Comment by thecortex** [comment]
Has this feature been implemented?

**Comment by dyve** [comment]
No, but a PR would be welcome.

**Comment by ralokt** [comment]
Is that still valid? Would like to give a `bootstrap_button` a `formaction`, and would be happy to do this, at least for buttons. A quick glance at the code tells me that this would be significantly easier than to do this for all renderers, since they use `**kwargs` already and we'd need to distinguish between "base"/"api" attributes and data attributes.

**Comment by dyve** [comment]
As long as the change does not clash with any Django standards I'd say go for it.
