### ISSUE TITLE
Error: Parameter "form" should contain a valid Django Form

### ISSUE THREAD

**Issue by seanhu24** [dyve/django-bootstrap3#425]
I followed the example using Parameter Django (2.0) and django-bootstrap3 (9.1.0) and it shows:
`

Request Method: | GET
-- | --
http://127.0.0.1:8000/polls/
2.0
BootstrapError
Parameter "form" should contain a valid Django Form.
D:\PycharmProjects\mysite\venv\lib\site-packages\bootstrap3\renderers.py in __init__, line 161
D:\PycharmProjects\mysite\venv\Scripts\python.exe
3.5.1
['D:\\PycharmProjects\\mysite',  'D:\\PycharmProjects\\mysite\\venv\\Scripts\\python35.zip',  'D:\\PycharmProjects\\mysite\\venv\\DLLs',  'D:\\PycharmProjects\\mysite\\venv\\lib',  'D:\\PycharmProjects\\mysite\\venv\\Scripts',  'C:\\Python\\Python35\\Lib',  'C:\\Python\\Python35\\DLLs',  'D:\\PycharmProjects\\mysite\\venv',  'D:\\PycharmProjects\\mysite\\venv\\lib\\site-packages']
Sun, 17 Dec 2017 15:35:23 +0800
`
following is my code:

`
{% load static %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<form action="/url/to/submit/" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Submit
    </button>
  {% endbuttons %}
</form>
`

**Comment by ikcam** [comment]
Can you send your `views.py` file?

**Comment by seanhu24** [comment]
here is my view file:
`
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


def detail(request, question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question':question})

def vote(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/index.html',{'question': question,\
                                                   'error_message': 'you did not choose a choice'})
    else:
        selected_choice.votes=selected_choice.votes+1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def index(request):
    latest_question_list=Question.objects.order_by('pub_date')[:5]
    context={'latest_question_list':latest_question_list}
    return render(request, 'polls/index.html', context)

class IndexView(generic.ListView):
    template_name='polls/index.html'
    context_object_name='latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name='polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


`

**Comment by gamugamu** [comment]
I have the same problem. I used the exemple in the doc, but as it is poorly explained, we don't understand why using the plain example triggers lot of templating errors.
For example: 
`{% bootstrap_form form %}`
Is not working and throw: 'Parameter "form" should contain a valid Django Form.' But what is a valid Django form? Since this is a template, I have no idea what it is done behind the scene.

I'm using django-bootstrap4:
` {% load bootstrap4 %}
`

Can you make some explicit exemple and HOW to resolve those templating syntax error? Like, why are you asking the code for the view/model? Does we have to pass a "form" object to the template? I feel like the documentation lacks some explication.
Thanks

**Comment by gamugamu** [comment]
Ok, for those who had the same problem as me: it is because the form from the model must override  forms.Form:
ex:

```
class UrlForm(forms.Form):
    url = forms.URLField(label='URL')
    title = forms.CharField(label='Title')
    nick = forms.CharField(label='Nick')
```

in the context (I work on wagtail, and there is no logic view like in django):
```
    def get_context(self, request):
        # Update context to include only published posts, ordered by reverse-chron
        form = forms.URLField(label='URL')
        context = super(BlogPage, self).get_context(request)
        context['form'] = form
        return context
```

Note that providing a bar ` x = forms.URLField(label='URL')` as form object like I did in my first try is invalid (And I have no idea why). I had to provide an overrided class from Form in order to generate the        ` {% bootstrap_form form %}`
template.

That's not a problem related to django-bootstrap. But the doc misguided me to think that the form templating could be directly generated without providing any django component. I don't think this is the case
